// Generated by Wrangler on Thu Sep 07 2023 15:15:03 GMT-0400 (Eastern Daylight Time)
interface Env {
	ORY_SDK_URL: "https://auth.thriv.systems";
	ORY_API_KEY: "";
	ORY_PRIVATE_API: "https://auth.thriv.systems";
	THRIVAPI_USER_BASE_URL: "https://api.thriv.systems/";
	THRIVAPI_ADMIN_BASE_URL: "https://admin.thriv.systems/";
}
