// Generated by Wrangler on Fri Sep 08 2023 01:29:40 GMT-0400 (Eastern Daylight Time)
interface Env {
	ORY_SDK_URL: "https://auth.thriv.systems";
	ORY_API_KEY: "";
	ORY_PRIVATE_API: "https://auth.thriv.systems";
	THRIVAPI_USER_BASE_URL: "https://api.thriv.systems";
	THRIVAPI_ADMIN_BASE_URL: "https://admin.thriv.systems";
	api: Fetcher;
}
