// Generated by Wrangler on Thu Sep 14 2023 01:39:34 GMT-0400 (Eastern Daylight Time)
interface Env {
	FACILITY: KVNamespace;
	LEGACY_PROFILE: KVNamespace;
	PROVIDER: KVNamespace;
	BOOKING: KVNamespace;
	PROFILE: KVNamespace;
	SERVICE: KVNamespace;
	USER: KVNamespace;
	ORY_SDK_URL: "https://auth.thriv.systems";
	ORY_PRIVATE_API: "https://auth.thriv.systems";
	ORY_API_KEY: string;
	USER_PROFILE: D1Database;
	USER_BOOKING: D1Database;
	FACILITY_PROVIDER: D1Database;
}
