// Generated by Wrangler on Tue Sep 05 2023 21:24:52 GMT-0400 (Eastern Daylight Time)
interface Env {
	FACILITY: KVNamespace;
	PROVIDER: KVNamespace;
	BOOKING: KVNamespace;
	PROFILE: KVNamespace;
	SERVICE: KVNamespace;
	USER: KVNamespace;
	ORY_SDK_URL: "http://localhost:4000";
	ORY_API_KEY: "secret";
	ORY_PRIVATE_API: "https://auth.thriv.systems/";
	USER_PROFILE: D1Database;
	USER_BOOKING: D1Database;
	FACILITY_PROVIDER: D1Database;
}
