// Generated by Wrangler on Thu Aug 31 2023 12:24:31 GMT-0400 (Eastern Daylight Time)
interface Env {
	FACILITY: KVNamespace;
	PROVIDER: KVNamespace;
	BOOKING: KVNamespace;
	PROFILE: KVNamespace;
	SERVICE: KVNamespace;
	USER: KVNamespace;
	ORY_SDK_URL: "https://auth.thriv.systems";
	USER_PROFILE: D1Database;
	USER_BOOKING: D1Database;
	FACILITY_PROVIDER: D1Database;
}
